/**
 * semantic-release configuration.
 *
 * Replaces the former `.releaserc.json`, which could not express the one thing
 * this setup needs: a plugin list that differs between the stable and the
 * prerelease branch.
 *
 * Prereleases on `develop` exist for exactly one reason — to give dev.cachy.app
 * a version string that differs from cachy.app. (Both sites once showed the same
 * number because develop's tags were unreachable from main; the `-beta.N` suffix
 * is what keeps them distinguishable.) That job only requires the version to land
 * in package.json and the commit to be tagged.
 *
 * What it does NOT require is a GitHub Release and a CHANGELOG section per
 * prerelease. At the observed rate — 38 prereleases for a single stable release —
 * those artifacts bury the handful of real releases they are supposed to
 * advertise. So the changelog and github plugins run on `main` only; `develop`
 * still gets its version and its tag, and the back-merge from main brings the
 * stable CHANGELOG entries back over.
 *
 * Branch detection uses GITHUB_REF_NAME, which Actions sets to the pushed branch
 * name. Outside CI the value is absent and we fall back to the full stable plugin
 * set, so a local `npx semantic-release --dry-run` reports what main would do
 * rather than silently omitting steps.
 */

const isStableBranch = (process.env.GITHUB_REF_NAME ?? "main") === "main";

// Note: these are plain string literals, not template literals — the `${...}`
// placeholders are interpolated by semantic-release, not by JavaScript.
const gitCommitMessage =
  "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}";

const changelogPlugin = [
  "@semantic-release/changelog",
  {
    changelogFile: "CHANGELOG.md",
    changelogTitle:
      "# Changelog\n\nAll notable changes to Cachy are documented here. This file is generated by\nsemantic-release from Conventional Commit messages — do not edit it by hand.\nThe 0.9x releases that preceded 1.0.0 were maintained manually and are kept in\n`docs/CHANGELOG-legacy.md`.",
  },
];

export default {
  branches: [
    "main",
    {
      name: "develop",
      prerelease: "beta",
    },
  ],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ...(isStableBranch ? [changelogPlugin] : []),
    [
      "@semantic-release/npm",
      {
        npmPublish: false,
      },
    ],
    [
      "@semantic-release/git",
      {
        // CHANGELOG.md is only touched on main, so only main commits it.
        assets: isStableBranch
          ? ["package.json", "package-lock.json", "CHANGELOG.md"]
          : ["package.json", "package-lock.json"],
        message: gitCommitMessage,
      },
    ],
    ...(isStableBranch ? ["@semantic-release/github"] : []),
  ],
};
