/*
 * Copyright (C) 2026 MYDCT
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// server.js
// Wrapper script to start the SvelteKit app with a default port of 3001
// This solves the issue where port 3000 is occupied on shared hosting (e.g. aaPanel)

// Set default port to 3001 if not already set via environment variable
process.env.PORT = process.env.PORT || "3001";

console.log(`Starting server on port ${process.env.PORT}...`);

// Import the SvelteKit build (generated by adapter-node)
// Note: This requires 'npm run build' to have been run first
await import("./build/index.js");
