/*
 * Copyright (C) 2026 MYDCT
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * BUG-0444 — the price builder's claim is its own round trip.
 *
 * The conditions are written out longhand, as in `conditionSlots.test.ts`: a
 * corpus generated by the builder would round-trip by construction.
 */

import { describe, expect, it } from "vitest";

import { buildPriceCondition, priceReadingOf } from "./priceFormLeaf";
import type { Condition } from "../rules/types";

const WRITTEN_BY_THE_BUILDER: Condition[] = [
  { kind: "cross", left: { kind: "price", field: "close" }, direction: "above", right: { kind: "constant", value: "61234.57" }, timeframe: "1h" },
  { kind: "cross", left: { kind: "price", field: "high", source: "mark" }, direction: "below", right: { kind: "constant", value: "0.00000012" }, timeframe: "4h" },
  { kind: "compare", left: { kind: "percent_change", field: "close", lookback: 3 }, op: "gte", right: { kind: "constant", value: "2.5" }, timeframe: "1h" },
  { kind: "compare", left: { kind: "percent_change", field: "low", source: "mark", lookback: 12 }, op: "lte", right: { kind: "constant", value: "-5" }, timeframe: "1d" },
];

describe("priceReadingOf", () => {
  it("reads every condition the builder writes back into a form that rebuilds it exactly", () => {
    for (const condition of WRITTEN_BY_THE_BUILDER) {
      const reading = priceReadingOf(condition);
      expect(reading, JSON.stringify(condition)).not.toBeNull();
      expect(buildPriceCondition(reading!, condition.timeframe)).toEqual(condition);
    }
  });

  it("reads the OHLC field and the series, not only the form", () => {
    expect(priceReadingOf(WRITTEN_BY_THE_BUILDER[1])).toEqual({
      form: { kind: "falls_below", threshold: "0.00000012", lookback: 1 },
      field: "high",
      source: "mark",
    });
  });

  it("reads a level spelled with trailing zeros as the same number", () => {
    // Rebuilt as "60000": the value the core evaluates does not change.
    const condition: Condition = { kind: "cross", left: { kind: "price", field: "close" }, direction: "above", right: { kind: "constant", value: "60000.00" }, timeframe: "1h" };
    expect(priceReadingOf(condition)?.form.threshold).toBe("60000");
  });

  it("reads nothing from a condition the builder does not write", () => {
    const notPrice: Condition = { kind: "compare", left: { kind: "volume" }, op: "gt", right: { kind: "constant", value: "1000" }, timeframe: "1h" } as unknown as Condition;
    expect(priceReadingOf(notPrice)).toBeNull();
    expect(priceReadingOf({ kind: "group", op: "all", of: [WRITTEN_BY_THE_BUILDER[0]] })).toBeNull();
  });
});
