/**
 * Copyright (C) 2026 MYDCT
 * 
 * I18n Validator & Type Generator
 * 
 * 1. Checks that all keys in en.json exist in de.json.
 * 2. Generates src/locales/schema.d.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const EN_PATH = path.join(__dirname, '../src/locales/locales/en.json');
const DE_PATH = path.join(__dirname, '../src/locales/locales/de.json');
const OUT_PATH = path.join(__dirname, '../src/locales/schema.d.ts');

function flattenKeys(obj, prefix = '') {
    let keys = [];
    for (const key in obj) {
        if (typeof obj[key] === 'object' && obj[key] !== null) {
            keys = keys.concat(flattenKeys(obj[key], prefix + key + '.'));
        } else {
            keys.push(prefix + key);
        }
    }
    return keys;
}

try {
    console.log('📖 Reading locales...');
    const enContent = fs.readFileSync(EN_PATH, 'utf-8');
    const deContent = fs.readFileSync(DE_PATH, 'utf-8');

    const enJson = JSON.parse(enContent);
    const deJson = JSON.parse(deContent);

    const enKeys = flattenKeys(enJson);
    const deKeys = flattenKeys(deJson);

    console.log('🔍 Validating keys...');
    const missingInDe = enKeys.filter(k => !deKeys.includes(k));

    if (missingInDe.length > 0) {
        console.error('❌ Missing keys in German translation:');
        missingInDe.forEach(k => console.error(`  - ${k}`));
        // We warn but continue to generate types
    } else {
        console.log('✅ All keys present in German translation.');
    }

    console.log('🔨 Generating types...');
    const unionType = enKeys.map(k => `  | "${k}"`).join('\n');

    const fileContent = `// Auto-generated by scripts/validate-i18n.js
// Do not edit manually

export type TranslationKey =
${unionType};
`;

    fs.writeFileSync(OUT_PATH, fileContent);
    console.log(`✅ Generated types at ${OUT_PATH}`);

    if (missingInDe.length > 0) {
        process.exit(1);
    }

} catch (err) {
    console.error('❌ Error:', err);
    process.exit(1);
}
