// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GlobalMessage = __t.object("GlobalMessage", {
  sender: __t.string(),
  text: __t.string(),
  sentAt: __t.f64(),
});
export type GlobalMessage = __Infer<typeof GlobalMessage>;

export const MessageCleanupSchedule = __t.object("MessageCleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MessageCleanupSchedule = __Infer<typeof MessageCleanupSchedule>;

